In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [70]:
import warnings
warnings.filterwarnings('ignore')

Corporate Styling

In [71]:
# plt.style.use('seaborn-v0_8')
# sns.set_palette('husi')

# print('Everythihng is fie')

### Load Dataset

In [72]:
df = pd.read_csv("./realistic_funnel_data.csv")

### Perform Basic Steps

In [73]:
print ("Top 5 data\n")
display(df.head())

Top 5 data

,User_ID,Session_ID,User_Type,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
0,USR00001,USR00001_SES0_58be9,New,Browse,2026-04-04 12:55:43,Tablet,North,Social Media,Beauty,0.0,No
1,USR00001,USR00001_SES0_58be9,New,Add to Cart,2026-04-04 12:57:43,Tablet,North,Social Media,Beauty,0.0,No
2,USR00001,USR00001_SES0_58be9,New,Checkout,2026-04-04 13:02:43,Tablet,North,Social Media,Beauty,0.0,No
3,USR00001,USR00001_SES1_c34a8,New,Browse,2026-04-05 12:55:43,Tablet,West,Google Ads,Electronics,0.0,Yes
4,USR00002,USR00002_SES0_ff5d9,New,Browse,2026-03-18 02:47:04,Tablet,North,Google Ads,Beauty,0.0,Yes

In [74]:
# last 5 rows
df.tail()

,User_ID,Session_ID,User_Type,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
39939,USR10000,USR10000_SES0_0cb60,Returning,Add to Cart,2026-03-18 16:43:18,Mobile,West,Social Media,Fashion,0.0,No
39940,USR10000,USR10000_SES0_0cb60,Returning,Checkout,2026-03-18 16:45:18,Mobile,West,Social Media,Fashion,0.0,No
39941,USR10000,USR10000_SES1_f30fb,Returning,Browse,2026-03-19 10:40:18,Tablet,North,Organic,Sports,0.0,No
39942,USR10000,USR10000_SES1_f30fb,Returning,Add to Cart,2026-03-19 10:42:18,Tablet,North,Organic,Sports,0.0,No
39943,USR10000,USR10000_SES2_7b5ad,Returning,Browse,2026-03-21 10:40:18,Mobile,North,Google Ads,Beauty,0.0,Yes

In [75]:
# Random data from dataset
df.sample()

,User_ID,Session_ID,User_Type,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
21481,USR05415,USR05415_SES2_c8113,New,Purchase,2026-04-06 06:58:58,Desktop,South,Google Ads,Electronics,3823.94,No

In [76]:
# Find total columns name and number of columnns
print(df.columns)
print(f"\nTOtal Number of Columns {df.columns.nunique()}")

Index(['User_ID', 'Session_ID', 'User_Type', 'Event', 'Timestamp', 'Device',
       'Region', 'Channel', 'Product_Category', 'Revenue', 'Bounce_Flag'],
      dtype='object')

TOtal Number of Columns 11

In [77]:
# Type of dataset
type(df)

pandas.core.frame.DataFrame

In [78]:
# datatype of all columns
df.dtypes

User_ID              object
Session_ID           object
User_Type            object
Event                object
Timestamp            object
Device               object
Region               object
Channel              object
Product_Category     object
Revenue             float64
Bounce_Flag          object
dtype: object

In [79]:
#timestam coolumn must be in the date time tdtype

df['Timestamp']=pd.to_datetime(df['Timestamp'])
print(df.dtypes)

User_ID                     object
Session_ID                  object
User_Type                   object
Event                       object
Timestamp           datetime64[ns]
Device                      object
Region                      object
Channel                     object
Product_Category            object
Revenue                    float64
Bounce_Flag                 object
dtype: object

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39944 entries, 0 to 39943
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           39944 non-null  object
 1   Session_ID        39944 non-null  object
 2   User_Type         39944 non-null  object
 3   Event             39944 non-null  object
 4   Timestamp         39944 non-null  datetime64[ns]
 5   Device            39944 non-null  object
 6   Region            39944 non-null  object
 7   Channel           39944 non-null  object
 8   Product_Category  39944 non-null  object
 9   Revenue           39944 non-null  float64
 10  Bounce_Flag       39944 non-null  object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 3.4+ MB

In [81]:
# imp information about dataset's numeric columns
df.describe()

                           Timestamp      Revenue
count                          39944  39944.00000
mean   2026-03-26 09:01:05.653164288     65.50803
min              2026-03-10 03:11:22      0.00000
25%    2026-03-19 04:52:02.750000128      0.00000
50%              2026-03-26 11:42:42      0.00000
75%       2026-04-02 13:07:13.500000      0.00000
max              2026-04-13 01:15:47   4980.92000
std                              NaN    364.28318

In [82]:
# imp information about all columns
df.describe(include = "object")

,User_ID,Session_ID,User_Type,Event,Device,Region,Channel,Product_Category,Bounce_Flag
count,39944,39944,39944,39944,39944,39944,39944,39944,39944
unique,10000,20091,2,4,3,4,4,5,2
top,USR07100,USR09039_SES0_cda2c,New,Browse,Tablet,South,Email,Sports,No
freq,12,4,26467,20091,13437,10253,10457,8047,32420

In [83]:
# shape of dataset
df.shape

(39944, 11)

In [84]:
# pd.set_option("display.max_rows",None)

In [85]:
# df

### Data preprocessing and cleaning

In [86]:
# Summary of dataset quality checks

# Null values
null_values = df.isnull().sum()

# Duplicate rows
duplicate_count = df.duplicated().sum()

# Unique values per column
unique_values = df.nunique()

# Display results
print("=== Data Quality Summary ===\n")

print("🔹Null Values per Column:")
print(null_values[null_values > 0])  # show only columns with nulls

print("\n🔹Total Duplicate Rows:")
print(duplicate_count)

print("\n🔹Unique Values per Column:")
print(unique_values)

=== Data Quality Summary ===

🔹Null Values per Column:
Series([], dtype: int64)

🔹Total Duplicate Rows:
0

🔹Unique Values per Column:
User_ID             10000
Session_ID          20091
User_Type               2
Event                   4
Timestamp           39636
Device                  3
Region                  4
Channel                 4
Product_Category        5
Revenue              1847
Bounce_Flag             2
dtype: int64

In [87]:
# Ensure Timestamp is in datetime format
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

# Create time-based features
df = df.assign(
    Date=df['Timestamp'].dt.date,
    DayOfWeek=df['Timestamp'].dt.day_name(),
    Hour=df['Timestamp'].dt.hour,
    WeekNumber=df['Timestamp'].dt.isocalendar().week.astype('int'),
)

In [88]:
# Create event sequence per session
df['Event_Sequence'] = df.groupby('Session_ID').cumcount().add(1)

In [89]:
df.head()

,User_ID,Session_ID,User_Type,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag,Date,DayOfWeek,Hour,WeekNumber,Event_Sequence
0,USR00001,USR00001_SES0_58be9,New,Browse,2026-04-04 12:55:43,Tablet,North,Social Media,Beauty,0.0,No,2026-04-04,Saturday,12,14,1
1,USR00001,USR00001_SES0_58be9,New,Add to Cart,2026-04-04 12:57:43,Tablet,North,Social Media,Beauty,0.0,No,2026-04-04,Saturday,12,14,2
2,USR00001,USR00001_SES0_58be9,New,Checkout,2026-04-04 13:02:43,Tablet,North,Social Media,Beauty,0.0,No,2026-04-04,Saturday,13,14,3
3,USR00001,USR00001_SES1_c34a8,New,Browse,2026-04-05 12:55:43,Tablet,West,Google Ads,Electronics,0.0,Yes,2026-04-05,Sunday,12,14,1
4,USR00002,USR00002_SES0_ff5d9,New,Browse,2026-03-18 02:47:04,Tablet,North,Google Ads,Beauty,0.0,Yes,2026-03-18,Wednesday,2,12,1

In [90]:
# Basic dataset summary

total_users = df['User_ID'].nunique()
total_sessions = df['Session_ID'].nunique()
date_min, date_max = df['Date'].agg(['min', 'max'])

print("=== Dataset Overview ===\n")
print(f"👤 Total Users      : {total_users}")
print(f"🧾 Total Sessions   : {total_sessions}")
print(f"📅 Date Range       : {date_min} → {date_max}")

=== Dataset Overview ===

👤 Total Users      : 10000
🧾 Total Sessions   : 20091
📅 Date Range       : 2026-03-10 → 2026-04-13

In [91]:
summary = {
    "Total Users": df['User_ID'].nunique(),
    "Total Sessions": df['Session_ID'].nunique(),
    "Start Date": df['Date'].min(),
    "End Date": df['Date'].max()
}

for k, v in summary.items():
    print(f"{k:<15}: {v}")

Total Users    : 10000
Total Sessions : 20091
Start Date     : 2026-03-10
End Date       : 2026-04-13

### Funnel Stage Definition and Session-Level Aggregation

In [92]:
# Define funnel stages
funnel_stages = ['Browse', 'Add to cart', 'Checkout', 'Purchase']

# Precompute stage ranking (avoids rebuilding dict every function call)
stage_rank = {stage: i for i, stage in enumerate(funnel_stages)}

# Sort data BEFORE grouping (important for correct event order)
df = df.sort_values(['Session_ID', 'Timestamp'])

# Create session-level summary
session_summary = (
    df.groupby('Session_ID')
      .agg(
          User_ID=('User_ID', 'first'),
          Session_Start=('Timestamp', 'min'),
          Session_End=('Timestamp', 'max'),
          Event_Sequence=('Event', list),
          Device=('Device', 'first'),
          Region=('Region', 'first'),
          Channel=('Channel', 'first'),
          Product_Category=('Product_Category', 'first'),
          Revenue=('Revenue', 'first'),
          Bounce_Flag=('Bounce_Flag', 'first')
      )
      .reset_index()
)

# Session duration (vectorized)
session_summary['Session_Duration_Min'] = (
    (session_summary['Session_End'] - session_summary['Session_Start'])
    .dt.total_seconds()
    .div(60)
)

# Optimized funnel stage detection
def get_max_funnel_stage(events):
    max_stage = -1
    for e in events:
        rank = stage_rank.get(e, -1)
        if rank > max_stage:
            max_stage = rank
    return funnel_stages[max_stage] if max_stage >= 0 else funnel_stages[0]

# Apply function
session_summary['Max_Funnel_Stage'] = session_summary['Event_Sequence'].apply(get_max_funnel_stage)

print("Session Summary Created:")
display(session_summary.head())

Session Summary Created:

,Session_ID,User_ID,Session_Start,Session_End,Event_Sequence,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag,Session_Duration_Min,Max_Funnel_Stage
0,USR00001_SES0_58be9,USR00001,2026-04-04 12:55:43,2026-04-04 13:02:43,"[Browse, Add to Cart, Checkout]",Tablet,North,Social Media,Beauty,0.0,No,7.0,Checkout
1,USR00001_SES1_c34a8,USR00001,2026-04-05 12:55:43,2026-04-05 12:55:43,[Browse],Tablet,West,Google Ads,Electronics,0.0,Yes,0.0,Browse
2,USR00002_SES0_ff5d9,USR00002,2026-03-18 02:47:04,2026-03-18 02:47:04,[Browse],Tablet,North,Google Ads,Beauty,0.0,Yes,0.0,Browse
3,USR00002_SES1_9f7d4,USR00002,2026-03-19 07:47:04,2026-03-19 07:52:04,"[Browse, Add to Cart]",Mobile,South,Google Ads,Sports,0.0,No,5.0,Browse
4,USR00003_SES0_42f5b,USR00003,2026-03-29 02:56:53,2026-03-29 03:02:53,"[Browse, Add to Cart]",Mobile,East,Email,Fashion,0.0,No,6.0,Browse

### Overall Funnel Analysis

In [93]:
# Calculate overall funnel metrics
funnel_metrics = []

total_sessions = len(session_summary)

for i, stage in enumerate(funnel_stages):
    if i == 0:
        # Browse stage: all sessions
        count = total_sessions
    else:
        # Other stages: sessions that reached at least this stage
        count = session_summary['Max_Funnel_Stage'].apply(
            lambda x: funnel_stages.index(x) >= i
        ).sum()
        
    funnel_metrics.append({
        'Stage': stage,
        'Sessions': count,
        'Stage_Order': i
    })

# Convert to DataFrame
funnel_df = pd.DataFrame(funnel_metrics)

# Conversion rate from first stage
funnel_df['Conversion_Rate'] = (funnel_df['Sessions'] / total_sessions * 100).round(2)

# Drop-off rate from previous stage
funnel_df['Drop_Off_Rate'] = (1 - funnel_df['Sessions'] / funnel_df['Sessions'].shift(1)).fillna(0) * 100
funnel_df['Drop_Off_Rate'] = funnel_df['Drop_Off_Rate'].round(2)

print("🎯 Overall Funnel Analysis:")
display(funnel_df)

🎯 Overall Funnel Analysis:

         Stage  Sessions  Stage_Order  Conversion_Rate  Drop_Off_Rate
0       Browse     20091            0           100.00           0.00
1  Add to cart      5434            1            27.05          72.95
2     Checkout      5434            2            27.05           0.00
3     Purchase      1852            3             9.22          65.92

### Visualization - Overall Funnel

In [94]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Prepare subplot
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Funnel Conversion Rates', 
        'Stage-to-Stage Drop-off (%)',
        'Revenue by Funnel Stage', 
        'Avg Session Duration by Stage (min)'
    ),
    specs=[[{"secondary_y": False}, {"secondary_y": False}],
           [{"secondary_y": False}, {"secondary_y": False}]]
)

# 1️⃣ Funnel Conversion Rates
fig.add_trace(
    go.Bar(
        x=funnel_df['Stage'], 
        y=funnel_df['Sessions'],
        text=funnel_df['Sessions'],
        textposition='auto',
        name='Sessions',
        marker_color='lightblue'
    ),
    row=1, col=1
)

# 2️⃣ Stage-to-Stage Drop-off
fig.add_trace(
    go.Scatter(
        x=funnel_df['Stage'], 
        y=funnel_df['Drop_Off_Rate'],
        mode='lines+markers+text',
        text=funnel_df['Drop_Off_Rate'].apply(lambda x: f"{x:.2f}%"),
        textposition='top center',
        name='Drop-off Rate',
        line=dict(color='red', width=3)
    ),
    row=1, col=2
)

# 3️⃣ Revenue by Funnel Stage
revenue_by_stage = session_summary.groupby('Max_Funnel_Stage')['Revenue'].sum().reindex(funnel_stages).fillna(0)
fig.add_trace(
    go.Bar(
        x=revenue_by_stage.index, 
        y=revenue_by_stage.values,
        text=[f"${x:,.0f}" for x in revenue_by_stage.values],
        textposition='auto',
        name='Revenue',
        marker_color='green'
    ),
    row=2, col=1
)

# 4️⃣ Avg Session Duration by Stage
duration_by_stage = session_summary.groupby('Max_Funnel_Stage')['Session_Duration_Min'].mean().reindex(funnel_stages).fillna(0)
fig.add_trace(
    go.Bar(
        x=duration_by_stage.index, 
        y=duration_by_stage.values.round(2),
        text=duration_by_stage.values.round(2),
        textposition='auto',
        name='Avg Session Duration',
        marker_color='orange'
    ),
    row=2, col=2
)

# Update layout
fig.update_layout(
    height=800, width=1000,
    title_text="🎯 Comprehensive Funnel Analysis Dashboard",
    showlegend=False,
    template='plotly_white'
)

fig.show()

### Channel Performance Analysis

In [95]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Standardize stage names
session_summary['Max_Funnel_Stage'] = session_summary['Max_Funnel_Stage'].str.strip().str.title()

channel_funnel = []

for channel, group in session_summary.groupby('Channel'):
    total_sessions = len(group)
    metrics = {'Channel': channel, 'Total_Sessions': total_sessions}

    # Stage-level sessions & rates
    for i, stage in enumerate(funnel_stages):
        if i == 0:
            count = total_sessions
        else:
            count = (group['Max_Funnel_Stage'].apply(lambda x: funnel_stages.index(x) >= i)).sum()
        metrics[f'{stage}_Sessions'] = count
        metrics[f'{stage}_Rate'] = round(count / total_sessions * 100, 2)

    # Revenue metrics
    purchase_sessions = group[group['Max_Funnel_Stage'] == 'Purchase']
    metrics['Total_Revenue'] = purchase_sessions['Revenue'].sum()
    metrics['AOV'] = purchase_sessions['Revenue'].mean() if len(purchase_sessions) > 0 else 0
    metrics['Conversion_Rate'] = round(len(purchase_sessions) / total_sessions * 100, 2)

    channel_funnel.append(metrics)

channel_df = pd.DataFrame(channel_funnel).sort_values('Conversion_Rate', ascending=False)

print("📊 Channel Performance Analysis:")
display(channel_df.round(2))

# --- Interactive Visualizations using Plotly ---
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=('Conversion Rate by Channel', 'Total Revenue by Channel',
                    'Average Order Value (AOV)', 'Session Distribution'),
    specs=[[{"type": "bar"}, {"type": "bar"}],
           [{"type": "bar"}, {"type": "pie"}]]
)

# Conversion Rate
fig.add_trace(go.Bar(
    x=channel_df['Channel'], y=channel_df['Conversion_Rate'],
    text=channel_df['Conversion_Rate'].apply(lambda x: f"{x}%"),
    textposition='auto', name='Conversion Rate', marker_color='lightblue'
), row=1, col=1)

# Total Revenue
fig.add_trace(go.Bar(
    x=channel_df['Channel'], y=channel_df['Total_Revenue'],
    text=channel_df['Total_Revenue'].apply(lambda x: f"${x:,.0f}"),
    textposition='auto', name='Total Revenue', marker_color='green'
), row=1, col=2)

# Average Order Value
fig.add_trace(go.Bar(
    x=channel_df['Channel'], y=channel_df['AOV'],
    text=channel_df['AOV'].apply(lambda x: f"${x:,.2f}"),
    textposition='auto', name='AOV', marker_color='orange'
), row=2, col=1)

# Session Distribution
fig.add_trace(go.Pie(
    labels=channel_df['Channel'],
    values=channel_df['Total_Sessions'],
    textinfo='label+percent',
    name='Session Distribution'
), row=2, col=2)

fig.update_layout(height=800, width=1000, title_text="📊 Channel Performance Dashboard", showlegend=False)
fig.show()

📊 Channel Performance Analysis:

,Channel,Total_Sessions,Browse_Sessions,Browse_Rate,Add to cart_Sessions,Add to cart_Rate,Checkout_Sessions,Checkout_Rate,Purchase_Sessions,Purchase_Rate,Total_Revenue,AOV,Conversion_Rate
0,Email,5159,5159,100.0,1410,27.33,1410,27.33,583,11.30,0.0,0.0,11.30
2,Organic,5023,5023,100.0,1427,28.41,1427,28.41,477,9.50,0.0,0.0,9.50
1,Google Ads,4900,4900,100.0,1348,27.51,1348,27.51,405,8.27,0.0,0.0,8.27
3,Social Media,5009,5009,100.0,1249,24.94,1249,24.94,387,7.73,0.0,0.0,7.73

### Regional Analysis

In [96]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# --- Regional Performance Summary ---
regional_analysis = session_summary.groupby('Region').agg(
    Total_Sessions=('Session_ID', 'count'),
    Total_Revenue=('Revenue', 'sum'),
    Avg_Session_Duration=('Session_Duration_Min', 'mean')
).round(2)

# Converted sessions & Conversion Rate
converted_sessions = session_summary[session_summary['Max_Funnel_Stage'] == 'Purchase'].groupby('Region').size()
regional_analysis['Converted_Sessions'] = converted_sessions
regional_analysis['Converted_Sessions'] = regional_analysis['Converted_Sessions'].fillna(0).astype(int)

regional_analysis['Conversion_Rate'] = (
    regional_analysis['Converted_Sessions'] / regional_analysis['Total_Sessions'] * 100
).round(2)

regional_analysis['AOV'] = (
    regional_analysis['Total_Revenue'] / regional_analysis['Converted_Sessions']
).fillna(0).round(2)

print("🌎 Regional Performance Summary:")
display(regional_analysis)

# --- Regional Funnel Progression (Interactive) ---
funnel_records = []

for region, group in session_summary.groupby('Region'):
    total_sessions = len(group)
    for i, stage in enumerate(funnel_stages):
        if i == 0:
            count = total_sessions
        else:
            count = (group['Max_Funnel_Stage'].apply(lambda x: funnel_stages.index(x) >= i)).sum()
        funnel_records.append({'Region': region, 'Stage': stage, 'Sessions': count})

regional_funnel_df = pd.DataFrame(funnel_records)

# Interactive line chart using Plotly
fig = go.Figure()

for region in regional_funnel_df['Region'].unique():
    df_region = regional_funnel_df[regional_funnel_df['Region'] == region]
    fig.add_trace(go.Scatter(
        x=df_region['Stage'], y=df_region['Sessions'],
        mode='lines+markers+text',
        text=df_region['Sessions'],
        textposition='top center',
        name=region
    ))

fig.update_layout(
    title="🌎 Funnel Progression by Region",
    xaxis_title="Funnel Stage",
    yaxis_title="Sessions",
    template='plotly_white',
    height=500,
    width=900
)

fig.show()

🌎 Regional Performance Summary:

,Total_Sessions,Total_Revenue,Avg_Session_Duration,Converted_Sessions,Conversion_Rate,AOV
Region,,,,,,
East,5054,0.0,3.92,465,9.20,0.0
North,4996,0.0,3.92,440,8.81,0.0
South,5108,0.0,4.05,501,9.81,0.0
West,4933,0.0,3.91,446,9.04,0.0

### Device and Product Category Analysis

In [97]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# --- Device Performance ---
device_analysis = session_summary.groupby('Device').agg(
    Total_Sessions=('Session_ID', 'count'),
    Revenue=('Revenue', 'sum'),
    Avg_Session_Duration=('Session_Duration_Min', 'mean'),
    Purchases=('Max_Funnel_Stage', lambda x: (x == 'Purchase').sum())
).round(2)

device_analysis['Conversion_Rate'] = (device_analysis['Purchases'] / device_analysis['Total_Sessions'] * 100).round(2)
device_analysis['AOV'] = (device_analysis['Revenue'] / device_analysis['Purchases']).fillna(0).round(2)

print("📱 Device Performance:")
display(device_analysis)

# --- Product Category Performance ---
product_analysis = session_summary.groupby('Product_Category').agg(
    Total_Sessions=('Session_ID', 'count'),
    Revenue=('Revenue', 'sum'),
    Purchases=('Max_Funnel_Stage', lambda x: (x == 'Purchase').sum())
).round(2)

product_analysis['Conversion_Rate'] = (product_analysis['Purchases'] / product_analysis['Total_Sessions'] * 100).round(2)
product_analysis['AOV'] = (product_analysis['Revenue'] / product_analysis['Purchases']).fillna(0).round(2)
product_analysis['Revenue_Per_Session'] = (product_analysis['Revenue'] / product_analysis['Total_Sessions']).round(2)

print("🏷️ Product Category Performance:")
display(product_analysis)

# --- Interactive Combined Visualization ---
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Conversion Rate by Device Type', 'Conversion Rate by Product Category')
)

# Device conversion rates
fig.add_trace(go.Bar(
    x=device_analysis.index,
    y=device_analysis['Conversion_Rate'],
    text=device_analysis['Conversion_Rate'].apply(lambda x: f"{x:.2f}%"),
    textposition='auto',
    name='Device Conversion Rate',
    marker_color='skyblue'
), row=1, col=1)

# Product category conversion rates
fig.add_trace(go.Bar(
    x=product_analysis.index,
    y=product_analysis['Conversion_Rate'],
    text=product_analysis['Conversion_Rate'].apply(lambda x: f"{x:.2f}%"),
    textposition='auto',
    name='Product Category Conversion Rate',
    marker_color='orange'
), row=1, col=2)

fig.update_layout(
    height=500, width=1000,
    title_text="📊 Device & Product Category Performance",
    showlegend=False,
    template='plotly_white'
)

fig.show()

📱 Device Performance:

,Total_Sessions,Revenue,Avg_Session_Duration,Purchases,Conversion_Rate,AOV
Device,,,,,,
Desktop,6715,0.0,4.00,693,10.32,0.0
Mobile,6667,0.0,3.85,505,7.57,0.0
Tablet,6709,0.0,4.00,654,9.75,0.0

🏷️ Product Category Performance:

,Total_Sessions,Revenue,Purchases,Conversion_Rate,AOV,Revenue_Per_Session
Product_Category,,,,,,
Beauty,3965,0.0,380,9.58,0.0,0.0
Electronics,4091,0.0,289,7.06,0.0,0.0
Fashion,3955,0.0,378,9.56,0.0,0.0
Home,4037,0.0,386,9.56,0.0,0.0
Sports,4043,0.0,419,10.36,0.0,0.0

### Time - Based Analysis

In [98]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# --- Daily Metrics ---
daily_metrics = df.groupby('Date').agg(
    Daily_Sessions=('Session_ID', 'nunique'),
    Daily_Users=('User_ID', 'nunique'),
    Daily_Revenue=('Revenue', 'sum')
)

# Daily conversions
daily_conversions = session_summary[session_summary['Max_Funnel_Stage'] == 'Purchase'].groupby(
    session_summary['Session_Start'].dt.date
).size()

daily_metrics['Daily_Conversions'] = daily_conversions
daily_metrics['Daily_Conversions'] = daily_metrics['Daily_Conversions'].fillna(0).astype(int)
daily_metrics['Daily_Conversion_Rate'] = (daily_metrics['Daily_Conversions'] / daily_metrics['Daily_Sessions'] * 100).round(2)

print("📅 Daily Performance Trends:")
display(daily_metrics.tail(10))

# --- Hourly Metrics ---
hourly_sessions = df.groupby('Hour').agg(
    Hourly_Sessions=('Session_ID', 'nunique'),
    Hourly_Revenue=('Revenue', 'sum')
)

hourly_conversions = session_summary[session_summary['Max_Funnel_Stage'] == 'Purchase'].copy()
hourly_conversions['Hour'] = hourly_conversions['Session_Start'].dt.hour
hourly_conversion_counts = hourly_conversions.groupby('Hour').size()

hourly_sessions['Hourly_Conversions'] = hourly_conversion_counts
hourly_sessions['Hourly_Conversions'] = hourly_sessions['Hourly_Conversions'].fillna(0).astype(int)
hourly_sessions['Hourly_Conversion_Rate'] = (hourly_sessions['Hourly_Conversions'] / hourly_sessions['Hourly_Sessions'] * 100).round(2)

# --- Interactive Visualization ---
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Daily Sessions Over Time',
        'Daily Conversion Rate (%)',
        'Hourly Sessions by Hour of Day',
        'Hourly Conversion Rate (%)'
    ),
    specs=[[{"type": "scatter"}, {"type": "scatter"}],
           [{"type": "bar"}, {"type": "bar"}]]
)

# Daily Sessions
fig.add_trace(go.Scatter(
    x=daily_metrics.index, y=daily_metrics['Daily_Sessions'],
    mode='lines+markers', name='Daily Sessions', line=dict(color='blue')
), row=1, col=1)

# Daily Conversion Rate
fig.add_trace(go.Scatter(
    x=daily_metrics.index, y=daily_metrics['Daily_Conversion_Rate'],
    mode='lines+markers', name='Daily Conversion Rate', line=dict(color='green')
), row=1, col=2)

# Hourly Sessions
fig.add_trace(go.Bar(
    x=hourly_sessions.index, y=hourly_sessions['Hourly_Sessions'],
    name='Hourly Sessions', marker_color='orange'
), row=2, col=1)

# Hourly Conversion Rate
fig.add_trace(go.Bar(
    x=hourly_sessions.index, y=hourly_sessions['Hourly_Conversion_Rate'],
    name='Hourly Conversion Rate', marker_color='red'
), row=2, col=2)

fig.update_layout(
    height=700, width=1000,
    title_text="📊 Daily & Hourly Performance Trends",
    showlegend=False,
    template='plotly_white'
)

fig.show()

📅 Daily Performance Trends:

,Daily_Sessions,Daily_Users,Daily_Revenue,Daily_Conversions,Daily_Conversion_Rate
Date,,,,,
2026-04-04,673,602,85516.12,62,9.21
2026-04-05,698,639,78153.58,59,8.45
2026-04-06,696,632,99368.44,65,9.34
2026-04-07,710,649,120206.38,84,11.83
2026-04-08,642,579,73057.83,49,7.63
2026-04-09,360,332,41448.34,33,9.17
2026-04-10,169,160,18073.87,15,8.88
2026-04-11,58,55,8122.84,7,12.07
2026-04-12,13,13,1505.77,1,7.69
2026-04-13,3,3,0.00,0,0.00

### Advanced Funnel Matrics and KPIs

In [99]:
# Calculate advanced metrics
print("🎯 KEY PERFORMANCE INDICATORS (KPIs)")
print("="*50)

# Overall KPIs
total_sessions = len(session_summary)
total_revenue = session_summary['Revenue'].sum()
total_orders = len(session_summary[session_summary['Max_Funnel_Stage'] == 'Purchase'])
overall_conversion_rate = (total_orders / total_sessions * 100)

print(f"📈 Overall Conversion Rate: {overall_conversion_rate:.2f}%")
print(f"💰 Total Revenue: ${total_revenue:,.2f}")
print(f"🛒 Average Order Value: ${(total_revenue / total_orders):.2f}")
print(f"👥 Total Sessions: {total_sessions:,}")
print(f"🎯 Total Orders: {total_orders:,}")

# Funnel efficiency metrics
browse_to_cart = (funnel_df.iloc[1]['Sessions'] / funnel_df.iloc[0]['Sessions'] * 100)
cart_to_checkout = (funnel_df.iloc[2]['Sessions'] / funnel_df.iloc[1]['Sessions'] * 100)
checkout_to_purchase = (funnel_df.iloc[3]['Sessions'] / funnel_df.iloc[2]['Sessions'] * 100)

print(f"\n🔄 Stage-to-Stage Conversion Rates:")
print(f"   Browse -> Add to Cart: {browse_to_cart:.2f}%")
print(f"   Add to Cart -> Checkout: {cart_to_checkout:.2f}%")
print(f"   Checkout -> Purchase: {checkout_to_purchase:.2f}%")

# Revenue per session at each stage
revenue_per_browse = total_revenue / funnel_df.iloc[0]['Sessions']
revenue_per_cart = total_revenue / funnel_df.iloc[1]['Sessions']
revenue_per_checkout = total_revenue / funnel_df.iloc[2]['Sessions']

print(f"\n💸 Revenue per Session by Stage:")
print(f"   Per Browse Session: ${revenue_per_browse:.2f}")
print(f"   Per Cart Session: ${revenue_per_cart:.2f}")
print(f"   Per Checkout Session: ${revenue_per_checkout:.2f}")

# Bounce rate analysis
bounce_sessions = session_summary[session_summary['Bounce_Flag'] == 'Yes']
bounce_rate = (len(bounce_sessions) / total_sessions * 100)
print(f"\n📉 Bounce Rate: {bounce_rate:.2f}%")

# Session duration analysis
avg_session_duration = session_summary['Session_Duration_Min'].mean()
print(f"⏱️ Average Session Duration: {avg_session_duration:.2f} minutes")

🎯 KEY PERFORMANCE INDICATORS (KPIs)
==================================================
📈 Overall Conversion Rate: 9.22%
💰 Total Revenue: $0.00
🛒 Average Order Value: $0.00
👥 Total Sessions: 20,091
🎯 Total Orders: 1,852

🔄 Stage-to-Stage Conversion Rates:
   Browse -> Add to Cart: 27.05%
   Add to Cart -> Checkout: 100.00%
   Checkout -> Purchase: 34.08%

💸 Revenue per Session by Stage:
   Per Browse Session: $0.00
   Per Cart Session: $0.00
   Per Checkout Session: $0.00

📉 Bounce Rate: 37.45%
⏱️ Average Session Duration: 3.95 minutes

### Strategic Recommendations

In [100]:
print("🎯 STRATEGIC RECOMMENDATIONS")
print("="*50)

# Biggest funnel drop-off
max_dropoff_stage = funnel_df.loc[funnel_df['Drop_Off_Rate'].idxmax()]
print(f"🚨 BIGGEST DROP-OFF: {max_dropoff_stage['Stage']} stage with {max_dropoff_stage['Drop_Off_Rate']:.2f}% drop-off")

# Best performing channel
best_channel = channel_df.loc[channel_df['Conversion_Rate'].idxmax()]
print(f"🏆 BEST PERFORMING CHANNEL: {best_channel['Channel']} with {best_channel['Conversion_Rate']:.2f}% conversion")

# Best performing region
best_region = regional_analysis.loc[regional_analysis['Conversion_Rate'].idxmax()]
print(f"🌍 BEST PERFORMING REGION: {best_region.name} with {best_region['Conversion_Rate']:.2f}% conversion")

# Best performing product category
best_category = product_analysis.loc[product_analysis['Conversion_Rate'].idxmax()]
print(f"🏷️ BEST PERFORMING CATEGORY: {best_category.name} with {best_category['Conversion_Rate']:.2f}% conversion")

# Recommended actions
print(f"\n💡 RECOMMENDED ACTIONS:")
print(f"1. Address '{max_dropoff_stage['Stage']}' stage drop-off with UX improvements")
print(f"2. Allocate more marketing budget to '{best_channel['Channel']}' channel")
print(f"3. Replicate strategies from '{best_region.name}' region in underperforming regions")
print(f"4. Promote '{best_category.name}' category to improve overall conversion")
checkout_dropoff = funnel_df.loc[funnel_df['Stage'] == 'Checkout', 'Drop_Off_Rate'].values[0]
print(f"5. Focus on cart abandonment recovery for {checkout_dropoff:.2f}% of users")

# Potential revenue opportunity
mean_aov = product_analysis['AOV'].dropna().mean()
cart_abandonment_sessions = funnel_df.loc[funnel_df['Stage'] == 'Checkout', 'Sessions'].values[0]
cart_abandonment_opportunity = cart_abandonment_sessions * mean_aov
print(f"\n💰 REVENUE OPPORTUNITY:")
print(f"   Cart abandonment recovery: ${cart_abandonment_opportunity:,.2f} potential revenue")

🎯 STRATEGIC RECOMMENDATIONS
==================================================
🚨 BIGGEST DROP-OFF: Add to cart stage with 72.95% drop-off
🏆 BEST PERFORMING CHANNEL: Email with 11.30% conversion
🌍 BEST PERFORMING REGION: South with 9.81% conversion
🏷️ BEST PERFORMING CATEGORY: Sports with 10.36% conversion

💡 RECOMMENDED ACTIONS:
1. Address 'Add to cart' stage drop-off with UX improvements
2. Allocate more marketing budget to 'Email' channel
3. Replicate strategies from 'South' region in underperforming regions
4. Promote 'Sports' category to improve overall conversion
5. Focus on cart abandonment recovery for 0.00% of users

💰 REVENUE OPPORTUNITY:
   Cart abandonment recovery: $0.00 potential revenue

### Export Results

In [103]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Prepare report data ---
report_data = {
    'Overall_Funnel': funnel_df,
    'Channel_Performance': channel_df,
    'Regional_Analysis': regional_analysis.reset_index(),
    'Device_Performance': device_analysis.reset_index(),
    'Product_Performance': product_analysis.reset_index(),
    'Daily_Trends': daily_metrics.reset_index(),
    'Hourly_Patterns': hourly_sessions.reset_index()
}

# --- Export to Excel ---
excel_file = 'funnel_analysis_report.xlsx'
with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
    for sheet_name, data in report_data.items():
        data.to_excel(writer, sheet_name=sheet_name, index=False)

print(f"✅ Analysis complete! Report exported to '{excel_file}'")

# --- Save key visualizations ---
# Funnel Conversion Rates
plt.figure(figsize=(10, 6))
sns.barplot(data=funnel_df, x='Stage', y='Conversion_Rate', palette='Blues_d')
plt.title('Overall Funnel Conversion Rates')
plt.ylabel('Conversion Rate (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('funnel_conversion_rates.png', dpi=300, bbox_inches='tight')
plt.close()

print("✅ Key visualizations saved as 'funnel_conversion_rates.png'")

✅ Analysis complete! Report exported to 'funnel_analysis_report.xlsx'
✅ Key visualizations saved as 'funnel_conversion_rates.png'